name: svt_taste
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  url_strategy: ^0.2.0
  url_launcher: ^6.1.5
  share_plus: ^4.0.10
  http: ^0.13.5
  step_progress_indicator: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  screenshot: ^1.2.3
  google_fonts: ^3.0.1
  firebase_core: ^1.20.0
  firebase_analytics: ^9.3.0
  image_picker_web: ^2.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

