name: svt_taste
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  url_strategy: ^0.2.0
  url_launcher: ^6.1.5
  share_plus: ^7.0.2
  http: ^1.0.0
  step_progress_indicator: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  screenshot: ^2.1.0
  google_fonts: ^4.0.5
  firebase_core: ^2.13.0
  firebase_analytics: ^10.4.1
  image_picker_web: ^3.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
